### ISSUE TITLE
5.4 compatibilty 

### ISSUE THREAD

**Issue by chrisbbreuer** [lakshmaji/Thumbnail#1]
Hi man,

I cant make a PR right now, but ThumbnailServiceProvider.php needs to be updated in order to compatible with Laravel 5.4.

Replace
```
$this->app['thumbnail'] = $this->app->share(function($app) {
      return new Thumbnail;
});
```

With 
```
$this->app->singleton('thumbnail', function($app) {
      return new Thumbnail;
});
```

Should be working then.

**Comment by lakshmaji** [comment]
Hi @Chinese1904 ,

Thank you very much for your support, we will update it to be compatible with Laravel 5.4 with reference to your suggestion #1. If you want to contribute you can create a pull request.

**Comment by lakshmaji** [comment]
Hi @Chinese1904 , updated the service container binding with the thumbnail package.

Once again thank you very much for your support........... :+1:  :)

**Comment by chrisbbreuer** [comment]
Perfect. Youre welcome and thanks for committing the update. I have been away from my work environment or else I would have sent in the PR

And thanks for the clip()
Love it!
