### ISSUE TITLE
Class 'FFMpeg\FFMpeg\FFMpeg' not found

### ISSUE THREAD

**Issue by namnguyenvn** [lakshmaji/Thumbnail#10]
Dear Lakshmaji,

I got this problem and I hope you can help me solve it:
After uploading the video to get the thumbnail I got this error: 
`FatalThrowableError in Thumbnail.php line 55:
Class 'FFMpeg\FFMpeg\FFMpeg' not found`

![capture](https://cloud.githubusercontent.com/assets/9395030/26522533/61fa8dd0-432d-11e7-8016-4dc687230a6f.PNG)

My configuration in .env is:
`##thumbnail video
#Thumbnail image dimensions
THUMBNAIL_IMAGE_WIDTH  = 320
THUMBNAIL_IMAGE_HEIGHT = 240

#Custom FFMPEG binaries path
FFMPEG_BINARIES=true
FFMPEG_PATH=C:\ffmpeg\bin\ffmpeg
FFPROBE_PATH=C:\ffmpeg\bin\ffprobe
FFMPEG_TIMEOUT=3600
FFMPEG_THREADS=12`

Thank you so much!

**Comment by lakshmaji** [comment]
Hi @namnguyenvn ,

Could you provide me the following details

- Regarding  development environment
   - [ ] OS  (I think it might be windows)
   - [ ] PHP version
   - [ ] Laravel Version
 
- Regarding Installation
   - [ ] Have you done with FFMpeg installation. (Install FFMpeg from  [this](http://www.wikihow.com/Install-FFmpeg-on-Windows) or [this](http://www.wikihow.com/Install-FFmpeg-on-Windows)  )
   - [ ] Have you done composer update

**Comment by namnguyenvn** [comment]
Hi @lakshmaji 

Thank you for your response.

I would like to send you the following details:
1. Development Environment: I use Laragon for developing this project.
a. OS: Windows 8.1
b. PHP version: PHP 7.1.1 (cli) (built: Jan 18 2017 18:51:14) ( ZTS MSVC14 (Visual C++ 2015) x86 )
c. Laravel version: 5.4
2. Installation
a. FFMpeg: I already follow the instruction in http://www.wikihow.com/Install-FFmpeg-on-Windows
![capture](https://cloud.githubusercontent.com/assets/9395030/26530524/820dae62-4400-11e7-9125-bb89471e8e1f.PNG)
b. Composer already updated the dependencies:
All my packages are:

C:\laragon\www\kmate.laravel (nam-dev)
λ composer show
alchemy/binary-driver                 1.6.0   A set of tools to build binary drivers
bkwld/croppa                          4.5.1   Image thumbnail creation through specially formatted URLs for Laravel
consoletvs/charts                     4.5.1   Create charts for laravel using diferent charts libraries
dnoegel/php-xdg-base-dir              0.1     implementation of xdg base directory specification for php
doctrine/cache                        v1.6.1  Caching library offering an object-oriented API for many cache backends
doctrine/inflector                    v1.1.0  Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                 1.0.5   A small, lightweight utility to instantiate objects in PHP without invoking their const...
erusev/parsedown                      1.6.2   Parser for Markdown.
evenement/evenement                   v2.0.0  Événement is a very simple event dispatching library for PHP
fzaninotto/faker                      v1.6.0  Faker is a PHP library that generates fake data for you.
guzzlehttp/guzzle                     6.2.3   Guzzle is a PHP HTTP client library
guzzlehttp/promises                   v1.3.1  Guzzle promises library
guzzlehttp/psr7                       1.4.2   PSR-7 message implementation that also provides common utility methods
hamcrest/hamcrest-php                 v1.2.2  This is the PHP port of Hamcrest Matchers
intervention/image                    2.3.13  Image handling and manipulation library with support for Laravel integration
jakub-onderka/php-console-color       0.1
jakub-onderka/php-console-highlighter v0.3.2
jlawrence/eos                         v3.2.2  Parse and solve math equations without using 'eval()'.
kkszymanowski/traitor                 0.2.3   Add a trait use statement to existing PHP class
lakshmaji/thumbnail                   v1.4.4  Thumbnails for videos
laravel/framework                     v5.4.23 The Laravel Framework.
laravel/tinker                        v1.0.0  Powerful REPL for the Laravel framework.
league/flysystem                      1.0.40  Filesystem abstraction: Many filesystems, one API.
maddhatter/laravel-fullcalendar       v1.2.4  Laravel helper for FullCalendar.io
mockery/mockery                       0.9.9   Mockery is a simple yet flexible PHP mock object framework for use in unit testing with...
monolog/monolog                       1.22.1  Sends your logs to files, sockets, inboxes, databases and various web services
mtdowling/cron-expression             v1.2.0  CRON for PHP: Calculate the next or previous run date and determine if a CRON expressio...
myclabs/deep-copy                     1.6.1   Create deep copies (clones) of your objects
nesbot/carbon                         1.22.1  A simple API extension for DateTime.
neutron/temporary-filesystem          2.2.0   Symfony filesystem extension to handle temporary files
nikic/php-parser                      v3.0.5  A PHP parser written in PHP
paragonie/random_compat               v2.0.10 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
pbmedia/laravel-ffmpeg                1.1.8   FFMpeg for Laravel 5.1 and higher
php-ffmpeg/php-ffmpeg                 0.9.3   FFMpeg PHP, an Object Oriented library to communicate with AVconv / ffmpeg
phpdocumentor/reflection-common       1.0     Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     3.1.1   With this component, a library can provide support for annotations via DocBlocks or oth...
phpdocumentor/type-resolver           0.2.1
phpspec/prophecy                      v1.7.0  Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             4.0.8   Library that provides collection, processing, and rendering functionality for PHP code ...
phpunit/php-file-iterator             1.4.2   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1   Simple template engine.
phpunit/php-timer                     1.0.9   Utility class for timing
phpunit/php-token-stream              1.4.11  Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       5.7.20  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          3.4.3   Mock Object library for PHPUnit
psr/http-message                      1.0.1   Common interface for HTTP messages
psr/log                               1.0.2   Common interface for logging libraries
psy/psysh                             v0.8.5  An interactive shell for modern PHP.
ramsey/uuid                           3.6.1   Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and ...
santigarcor/laratrust                 3.2.3   This package provides a flexible way to add Role-based Permissions to Laravel
sebastian/code-unit-reverse-lookup    1.0.1   Looks up which function or method a line of code belongs to
sebastian/comparator                  1.2.4   Provides the functionality to compare PHP values for equality
sebastian/diff                        1.4.3   Diff implementation
sebastian/environment                 2.0.0   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    2.0.0   Provides the functionality to export PHP variables for visualization
sebastian/global-state                1.1.1   Snapshotting of global state
sebastian/object-enumerator           2.0.1   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context           2.0.0   Provides functionality to recursively process PHP variables
sebastian/resource-operations         1.0.0   Provides a list of PHP built-in functions that operate on resources
sebastian/version                     2.0.1   Library that helps with managing the version number of Git-hosted PHP projects
swiftmailer/swiftmailer               v5.4.8  Swiftmailer, free feature-rich PHP mailer
symfony/console                       v3.2.8  Symfony Console Component
symfony/css-selector                  v3.2.8  Symfony CssSelector Component
symfony/debug                         v3.2.8  Symfony Debug Component
symfony/event-dispatcher              v3.2.8  Symfony EventDispatcher Component
symfony/filesystem                    v3.2.8  Symfony Filesystem Component
symfony/finder                        v3.2.8  Symfony Finder Component
symfony/http-foundation               v3.2.8  Symfony HttpFoundation Component
symfony/http-kernel                   v3.2.8  Symfony HttpKernel Component
symfony/polyfill-mbstring             v1.3.0  Symfony polyfill for the Mbstring extension
symfony/process                       v3.2.8  Symfony Process Component
symfony/routing                       v3.2.8  Symfony Routing Component
symfony/translation                   v3.2.8  Symfony Translation Component
symfony/var-dumper                    v3.2.8  Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                          v3.2.8  Symfony Yaml Component
tijsverkoyen/css-to-inline-styles     2.2.0   CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-pag...
vlucas/phpdotenv                      v2.4.0  Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagic...
watson/active                         2.0.4   Laravel helper for recognising the current route, controller and action
webmozart/assert                      1.2.0   Assertions to validate method input/output with nice error messages.
webpatser/laravel-uuid                2.0.1   Class to generate a UUID according to the RFC 4122 standard. Support for version 1, 3, ...
weotch/phpthumb                       1.0.5   Fork of PHPThumb that adds auto-image rotation based on EXIF data and composer support

**Comment by namnguyenvn** [comment]
Hi @lakshmaji,

I found the solution, just don't add any configuration to .env file.

Thanks!

**Comment by oindypoind** [comment]
I also have this problem
![image](https://cloud.githubusercontent.com/assets/341036/26721497/f01859bc-4783-11e7-8c09-703e963eec9c.png)
OS: windows 7
PHP: 5.6
Laravel: 5.4.24

FFMpeg is installed via linked tutorial
Composer is updated.

I have placed in my .ENV the following

FFMPEG_BINARIES=true
FFMPEG_PATH=C:\FFMPEG\bin\ffmpeg.exe
FFPROBE_PATH=C:\FFMPEG\bin\ffprobe.exe

Without these it was throwing an earlier error for not finding ffprobe.
