### ISSUE TITLE
why did you use try catch at lakshmaji/thumbnail/Thumbnail.php  line 109

### ISSUE THREAD

**Issue by hare2011** [lakshmaji/Thumbnail#11]
throw new Exception("Got bad cookie"); 
the code is hidden the real error message.
i advise you delete try catch code.

**Comment by gauthami123** [comment]
Got bad cookie
--
in Thumbnail.php (line 109)

**Comment by lakshmaji** [comment]
Hello,
Could you try the latest version [here](https://github.com/lakshmaji/Thumbnail/releases/tag/1.4.51)
