### ISSUE TITLE
having issue while creating thumbnail

### ISSUE THREAD

**Issue by thanush** [lakshmaji/Thumbnail#15]
my code is like below please check it and correct me if i'm wrong

    public function index(Request $request)

    {
    	$file = $request->file('file');
    	$fb_user_id = 'user';

    	$extension_type   = $file->getClientMimeType();
    	$destination_path = public_path().'/uploads';

    	$extension        = $file->getClientOriginalExtension();
    	$timestamp        = str_replace([' ', ':'], '-', Carbon::now()->toDateTimeString());
    	$file_name        = $timestamp;
    	$upload_status    = $file->move($destination_path, $file_name);
	    if($upload_status)
	    {
	      // file type is video
	      // set storage path to store the file (image generated for a given video)

	      $thumbnail_path   = public_path().'/images';

	      $video_path       = $destination_path.'/'.$file_name;

	      // set thumbnail image name
	      $thumbnail_image  = $file_name.".jpg";
    	  // $fp = fopen($thumbnail_path.'/'.$thumbnail_image, "w");

	      // dd($thumbnail_path.'/'.$thumbnail_image);
	      // set the thumbnail image "palyback" video button
	      $water_mark       = public_path().'/watermark/p.png';

	      // get video length and process it
	      // assign the value to time_to_image (which will get screenshot of video at that specified seconds)
	      $time_to_image    = '100';

	      $thumbnail_status = Thumbnail::getThumbnail($video_path,$thumbnail_path,$thumbnail_image);
	      // dd($thumbnail_status);
	      if($thumbnail_status)
	      {
	        echo "Thumbnail generated";
	      }
	      else
	      {
	        echo "thumbnail generation has failed";
	      }
	    }
    	// dd($file_name);
    }`

**Comment by lakshmaji** [comment]
@thanush it is fine, you are trying see the outcome.

- $thumbnail_status contain just a Boolean as return value
- $filename is generated by code you have in controller (replaces the actual file name with current timestamp) 
```php
$extension_type   = $file->getClientMimeType();
	$destination_path = public_path().'/uploads';

	$extension        = $file->getClientOriginalExtension();
	$timestamp        = str_replace([' ', ':'], '-', Carbon::now()->toDateTimeString());
	$file_name        = $timestamp;
```
