### ISSUE TITLE
Laravel 5.6 compatibility

### ISSUE THREAD

**Issue by hussonkevin** [lakshmaji/Thumbnail#17]
Hi,
Could you add support for Laravel 5.6 ?
Thanks a lot.

**Comment by lakshmaji** [comment]
Hi @hussonkevin ,
Sure, and any PR will be welcome.

**Comment by lakshmaji** [comment]
Actually the current package is compatible with Laravel 5.6 (My bad i realized now)

**Comment by lakshmaji** [comment]
Updated README file as well for beginners here 4b6e61b9d3996abddefd3e60f1fe4b615b284769
