### ISSUE TITLE
Thumbnail for video url

### ISSUE THREAD

**Issue by assoft** [lakshmaji/Thumbnail#2]
It is possible to receive thumnail from a remote file (youtube, dailymotion, Vimeo, etc...) ?

**Comment by chrisbbreuer** [comment]
Yes, if you have SSH/terminal access. This plugin doesn't support it and I don't see if supporting it in future as you need other dependencies. But you can set it up yourself: http://superuser.com/questions/680323/processing-youtube-video-in-ffmpeg

**Comment by lakshmaji** [comment]
Hi @assoft  ,

I haven't tested it with the live URL links like video URL from youtube, dailymotion etc., You are welcome to test that feature with this package if interested....
