### ISSUE TITLE
Resizing does not work

### ISSUE THREAD

**Issue by recoverjp** [lakshmaji/Thumbnail#20]
It's resizing with height of 400, but in my thumbnail.php I've set dimensions.height to 240. What can it be?

**Comment by kennygomel** [comment]
Met the same problem

**Comment by lakshmaji** [comment]
Could any of you guys paste the code from **.env**, **config.php** file where the configurations are made and the **upload snippet** here. So that we can resolve this.

Apart from that paste the environment details

- Laravel framework version
- composer version
- FFMpeg version
- PHP version
- OS

**Comment by lakshmaji** [comment]
@recoverjp, @kennygomel, Could any of you guys provide the reproducible steps here

**Comment by lakshmaji** [comment]
Closing this as we have insufficient information.
