### ISSUE TITLE
Not working with laravel 5.8. Status true but image not created in server.

### ISSUE THREAD

**Issue by samnantham** [lakshmaji/Thumbnail#26]
Not working with laravel 5.8. Status true but image not created in server. no issue when running but image not created from destination folder.

**Comment by nikulvnnovate** [comment]
same issue here with laravel 5.7.28

**Comment by AjithLalps** [comment]
are you developing on a windows system?

**Comment by nikulvnnovate** [comment]
NO google cloud ubuntu

**Comment by nikulvnnovate** [comment]
Its working issue is in code thanks for reply

**Comment by lakshmaji** [comment]
Closing as duplicate #25
