### ISSUE TITLE
Package update

### ISSUE THREAD

**Issue by adepolas** [lakshmaji/Thumbnail#5]
Hello

I am writing code with Laravel and I am not able to retrieve your latest merge (of branch adepolas-patch-2) from composer.

I've done a composer update. But the class Thumbnail.php remains the same. 

Do you know why ?

**Comment by lakshmaji** [comment]
Hi @adepolas ,
Actually we need to make a release to be able to load the Thumbnail.php changes from composer.

But, I was planning to add some new features and then release the new version.

**Comment by adepolas** [comment]
Ok @lakshmaji 👍 

What are the features you want to add ? What's the deadline ?

**Comment by lakshmaji** [comment]
@adepolas ,

We have update the package. Shall we close this issue?
