### ISSUE TITLE
 Call to undefined function Lakshmaji\Thumbnail\imagecreatefrompng()

### ISSUE THREAD

**Issue by nasznjoka** [lakshmaji/Thumbnail#6]
FatalThrowableError in Thumbnail.php line 84: Call to undefined function Lakshmaji\Thumbnail\imagecreatefrompng()

Ubuntu 16.4 php 7

**Comment by lakshmaji** [comment]
Hi @nasznjoka ,

Can you describe the statements that you are using to make the call .
You might be missing some parameters

**Comment by lakshmaji** [comment]
@nasznjoka 
Have you got the solution Is your problem got resolved?
