### ISSUE TITLE
Thumbnail.php config problem ?

### ISSUE THREAD

**Issue by adepolas** [lakshmaji/Thumbnail#7]
Hi again

Got bad cookie in /vendor/lakshmaji/thumbnail/src/Thumbnail.php:109

I haven't changed anything, just did the update for the package and it is broken. I am getting the "Got bad cookie" error..

**Comment by adepolas** [comment]
@config('thumbnail.binaries.enabled') is returning NULL but I've put FFMPEG_BINARIES to TRUE

**Comment by lakshmaji** [comment]
Hi @adepolas , for the new version the method prototype has been changed could you please revise the method [here](https://github.com/lakshmaji/Thumbnail#miscellaneous) 
And make sure that you have published the config file i.e., thumbnail.php
If still your are getting error let me know about that.

**Comment by adepolas** [comment]
I found the solution
Actually config('thumbnail.binaries.enabled') is returning null

Because you have to define the following line to your register method to your ServiceProvider : 
$this->mergeConfigFrom(__DIR__.'/config/thumbnail.php', 'thumbnail');

You can see it on my pull request https://github.com/lakshmaji/Thumbnail/pull/8

**Comment by lakshmaji** [comment]
Hi
I have tested the current package (version 1.4.4) and it is able to fetch the values from both **.env** and **thumbnail.php** files successfully.

- Make sure that you have restarted the server or local development server once after .env file has got updated. (This is must, as laravel **cache** system will hold the .env variable values at initial run]
- Make sure that you have published the configuration file **thumbnail.php** file to your **config** directory (by issuing the following command)
   ```bash
   php artisan vendor:publish
   ```

- Sample .env file I have used for testing
   ```ruby
   FFMPEG_BINARIES=true
   FFMPEG_PATH=/opt/local/ffmpeg/bin/ffmpeg
   FFPROBE_PATH=/opt/local/ffmpeg/bin/ffprobe
   FFMPEG_TIMEOUT=3600
   FFMPEG_THREADS=12
   ```
  
------------------------

**Note:** No spaces are allowed between the .env file variable and its values after the assignment operator. ( **=** )

Example:
**Invalid** ❌ 
```go
FFMPEG_BINARIES = true
```
**Valid**  ✔️  
```go 
FFMPEG_BINARIES=true 
```



Hope this helps 

--------------------------

#### If issue still persists please provide the development environment 
example

- [x] Laravel version 5.2
- [x] Thumbnail version 1.4.2
- [x] OS Ubuntu or your cool Mac Book 😉 
- [x] and finally the application server Apache or Nginx etc.

**Comment by adepolas** [comment]
Thanks for the details, php artisan vendor:publish worked for me !

**Comment by sytay** [comment]
Got bad cookie
--
in Thumbnail.php (line 109)

**Comment by lakshmaji** [comment]
@sytay this was due to thumbnail exception handler, will planning to fix it. If you are interested you can create PR

**Comment by gauthami123** [comment]
Got bad cookie
--
in Thumbnail.php (line 109)
